In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("hourly_weather_mannheim_2021.csv")
df

,time,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
0,2021-01-04 00:00:00,1.1,0.8,98,0.0,0.0,60,2.2,4.0,1013.8,0.0,8
1,2021-01-04 01:00:00,1.2,0.9,98,0.0,0.0,50,1.8,8.0,1013.8,0.0,1
2,2021-01-04 02:00:00,1.3,1.0,98,0.0,0.0,30,2.9,8.0,1013.6,0.0,1
3,2021-01-04 03:00:00,1.3,1.0,98,0.0,0.0,50,3.2,10.0,1013.9,0.0,1
4,2021-01-04 04:00:00,1.3,0.9,97,0.0,0.0,30,3.6,10.0,1013.9,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-10-03 19:00:00,17.7,14.6,82,0.0,NaN,200,13.7,25.0,1009.4,0.0,8
8756,2021-10-03 20:00:00,17.4,14.3,82,0.0,NaN,210,13.3,22.0,1010.6,0.0,4
8757,2021-10-03 21:00:00,17.0,14.1,83,0.0,NaN,210,12.6,26.0,1011.9,0.0,4
8758,2021-10-03 22:00:00,16.3,14.0,86,0.0,NaN,190,10.4,21.0,1013.3,0.0,8
8759,2021-10-03 23:00:00,15.5,14.0,91,0.3,NaN,190,8.3,17.0,1014.3,0.0,8